dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
install:
  - pip install -r requirements.txt
script:
  - cd $TRAVIS_BUILD_DIR
  - echo "Current directory is $(pwd)"
  - coverage run -m pytest --doctest-modules
  - coverage report -m
  - coverage xml -i
