dist: xenial   # required for Python >= 3.7
env:
  global:
    - CC_TEST_REPORTER_ID=$CODE_CLIMATE_REPORTER_ID
language: python
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - cd $TRAVIS_BUILD_DIR
  - echo "Current directory is $(pwd)"
  - coverage run -m pytest --doctest-modules
  - coverage report -m
  - coverage xml -i
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
